AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Lambda-Kansai official website API

Resources:
  KotolabBlogApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Dev
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Content-Sha256
        MaxAge: 600
        AllowCredentials: false

  KotolabBlogApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs20.x
      CodeUri: ./dist
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps
      Events:
        CatchAllRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref KotolabBlogApi
            Path: /{proxy+}
            Method: ANY
