name: CI on blog-lib

on:
  workflow_call:

jobs:
  ci-lib:
    runs-on: ubuntu-latest
    steps:
      # Setup Nix envirionment
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: cachix/cachix-action@v10
        with:
          name: katsujukou-github
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: nicknovitski/nix-develop@v1
      - run: nix develop --extra-experimental-features "nix-command flakes"

      # Run CI jobs
      - name: Install 
        run: spago install 
      - name: Build
        run: |
          spago build -p kotolab-blog-lib \
            && spago build -p kotolab-blog-foreign
            && spago build -p kotolab-blog-api-scheme

      - name: Test
        run: |
          spago test -p kotolab-blog-lib \
            && spago test -p kotolab-blog-foreign
  
      - name: Check
        run: purs-tidy check lib foreign api-scheme
