name: CI

on:
  push:
    paths:
      - '**'
      - '!.vscode/'
      - '!README.md'
  pull_request:
    paths:
      - '**'
      - '!.vscode/'
      - '!README.md'

jobs:
  lib:
    name: Build, Test & Check lib
    runs-on: ubuntu-latest
    uses: ./.github/workflows/nix.yaml
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: spago build -p kotolab-blog-lib && spago build -p kotolab-blog-foreign
      - name: Test
        run: spago test -p kotolab-blog-lib && spago test -p kotolab-blog-foreign
      - name: Check 
        run: purs_tidy check lib foreign

  web:
    name: Build, Test, Check & Deploy Web 
    runs-on: ubuntu-latest
    uses: ./.github/workflows/nix.yaml
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: spago build -p web
      - name: Run tests
        run:  spago test -p web
      - name: Check format
        run: purs-tidy check web
      - name: deploy
        run: cd web && pnpm install && pnpm release
        