name: CI

on:
  push:
    paths:
      - '**'
      - '!.vscode/'
      - '!README.md'
  pull_request:
    paths:
      - '**'
      - '!.vscode/'
      - '!README.md'

jobs:
  lib:
    name: Build, Test & Check lib
    uses: ./.github/workflows/_lib.yaml
    
  web:
    name: Build, Test, Check & Deploy Web 
    uses: ./.github/workflows/_web.yaml