name: CI

on:
  push:
    paths:
      - '**'
      - '!.vscode/'
      - '!README.md'
  pull_request:
    paths:
      - '**'
      - '!.vscode/'
      - '!README.md'

jobs:
  lib:
    name: Build, Test & Check lib
    runs-on: ubuntu-latest
    uses: ./.github/workflows/ci-lib.yaml
    
  web:
    name: Build, Test, Check & Deploy Web 
    runs-on: ubuntu-latest
    uses: ./.github/workflows/nix.yaml